[tasks.BUILD]
description = "Build project for development"
script = ['''
#!/bin/bash
cargo build --features bevy/dynamic_linking
''']

[tasks.DEV]
description = "Run project for development"
script = ['''
#!/bin/bash
cargo run --features bevy/dynamic_linking
''']

[tasks.wasmDEV]
description = "Run project for development"
script = ['''
#!/bin/bash
cargo run --target wasm32-unknown-unknown --features bevy/dynamic_linking
''']

[tasks.RELEASE]
description = "Build project for release"
script = ['''
#/bin/bash
cargo build --release
''']

[tasks.wasmRELEASE]
description = "Build project for release"
script = ['''
#/bin/bash
cargo build --target wasm32-unknown-unknown --release
''']

[tasks.wasmDEPLOY]
description = "create wasm directory to deploy, and launch the local server to test"
script = ['''
#!/bin/bash
rm -r ./docs/*
wasm-bindgen --no-typescript --target web --out-dir ./docs --out-name "dynamicarena" ./target/wasm32-unknown-unknown/release/dynamicarena.wasm
cp -r assets ./docs/assets
cp ./wasm_build/index.html docs/index.html

temp_file=$(mktemp)
cat ./wasm_build/enable_sound.js ./docs/dynamicarena.js > $temp_file
mv $temp_file ./docs/dynamicarena.js

cd docs/assets/images
rm *.blend
rm *.blend1
cd ../
rm README.md
cd ../../
python3 -m http.server 8000
''']
